### ISSUE TITLE
todo-list

### ISSUE THREAD

**Issue by nbeernink** [nbeernink/domain-inventory#1]
- [ ] handle subdomains better (either strip or process differently)
- [ ] match www to non-www records for domains
- [x] add -s parameter that takes a servername. This logs into the remote server to pull a list of domains (Plesk and DirectAdmin)
- [ ] improve domains_resolving.txt stat better (domains with multiple A records are incorrectly counted double at the moment)
- [x] if there are 0 unaligned domains, don't color red
- [ ] add an option custom record queries and show stats on which domains match and don't match; format: TXT, value
- [ ] add better filtering for a-record analysis (check if domain resolves but doesn't have A-records)
- [ ] add domain validation
- [ ] add checks for proper tools (sed,awk,etc should not be OSX' version because they are missing parameters that we're using)
- [x] switch realpath to readlink -f or some other way to find the full path to a file
